spring:
  datasource:
    url: jdbc:h2:~/data/restaurant
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
jwt:
  secret: 12345678901234567890123456789012

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test